# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\nf-interpreter\build'
  partitionsDirectory: '$(Build.SourcesDirectory)\nf-interpreter\targets\FreeRTOS_ESP32\_IDF\$(IDF_Target)'

steps:

  - task: CMake@1
    condition: succeeded()
    displayName: Setup build with CMake
    inputs:
      cmakeArgs: ' -G Ninja -DESP32_IDF_SOURCE=$(IDF_PATH) -DCMAKE_TOOLCHAIN_FILE=CMake/$(TOOLCHAINFILE) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_BOARD=$(TargetBoard) -DTARGET_NAME=$(TargetPublishName) $(BuildOptions) ..'
      workingDirectory: ${{ parameters.buildDirectory }}

  - task: CMake@1
    displayName: Build with CMake
    condition: succeeded()
    inputs:
      cmakeArgs: '--build . '
      workingDirectory:  ${{ parameters.buildDirectory }}

  # because of permission issues (the python script isn't allowed to write on the output folder)
  # we need to perform these steps by calling directly the python scripts
  - task: PythonScript@0
    condition: succeeded()
    displayName: Generate ESP32 Partition tables for 16MB flash
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(IDF_PATH)\components\partition_table\gen_esp32part.py'
      arguments: '--verify ${{ parameters.partitionsDirectory }}\partitions_nanoclr_16mb.csv ${{ parameters.buildDirectory }}\partitions_16mb.bin'
  - task: PythonScript@0
    condition: succeeded()
    displayName: Generate ESP32 Partition tables for 8MB flash
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(IDF_PATH)\components\partition_table\gen_esp32part.py'
      arguments: '--verify ${{ parameters.partitionsDirectory }}\partitions_nanoclr_8mb.csv ${{ parameters.buildDirectory }}\partitions_8mb.bin'

  - task: PythonScript@0
    condition: succeeded()
    displayName: Generate ESP32 Partition tables for 4MB flash
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(IDF_PATH)\components\partition_table\gen_esp32part.py'
      arguments: '--verify ${{ parameters.partitionsDirectory }}\partitions_nanoclr_4mb.csv ${{ parameters.buildDirectory }}\partitions_4mb.bin'

  - task: PythonScript@0
    condition: succeeded()
    displayName: Generate ESP32 Partition tables for 2MB flash
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(IDF_PATH)\components\partition_table\gen_esp32part.py'
      arguments: '--verify ${{ parameters.partitionsDirectory }}\partitions_nanoclr_2mb.csv ${{ parameters.buildDirectory }}\partitions_2mb.bin'
